services:
  # 1. MySQL 컨테이너
  mysql:
    image: mysql:8.0
    container_name: my-auth-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: wsd            # 생성할 DB 이름
    ports:
      - "3308:3306"
    volumes:
      - ./db_data:/var/lib/mysql     # 데이터 영구 저장을 위한 볼륨 매핑
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # 2. Redis 컨테이너
  redis:
    image: redis:alpine
    container_name: my-auth-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data